version: "2"

engines:
  plugins:
    pylint:
      enabled: true
      checks:
        invalid-name:
          enabled: false # disabled due to pylint mistaking variables for consts

exclude_patterns:
  - .git/**/*
