version: "2"

plugins:
  bandit:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
    checks:
      invalid-name:
        enabled: false # disabled due to pylint mistaking variables for consts
  sonar-python:
    enabled: true

exclude_patterns:
  - .git/**/*
